name: Update Changelog and Pubspec

permissions:
  contents: write

on:
  push:
    branches:
      - "0.*"
      - "v0.*"

jobs:
  changelog:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Update Changelog
        run: ./scripts/update_changelog.sh

      - name: Update pubspec.yaml version
        run: ./scripts/update_pubspec_version.sh

      - name: Commit changes if any
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add CHANGELOG.md pubspec.yaml
            git commit -m "chore: update changelog for $(cat VERSION)"
            git push origin HEAD:${{ github.ref_name }}
          fi
